apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "rabbitmq.fullname" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "rabbitmq.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
          - containerPort: 5672
          - containerPort: 15672
 
